### ISSUE TITLE
O comprimento nao pode ser maior que 105 cm

### ISSUE THREAD

**Issue by matheusvetor** [prodis/correios-frete#12]
Estou montando um pacote e o cálculo está me retornando R$ 0,00. Fui ver no log e o serviço está retornando o erro:
<Erro>-15</Erro><MsgErro><![CDATA[O comprimento nao pode ser maior que 105 cm.]]></MsgErro>

Meu pacote possui n produtos, quando efetuo o cálculo de um pacote muito grande ele me retorna o erro acima. Antes de ler o código, eu tentei adicionar pacotes dinamicamente  quando o pacote atual estivesse cheio. Só que o método encomenda recebe apenas 1 pacote. Existe alguma forma de contornar essa situação?

Segue abaixo o request:

http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?sCepOrigem=40040050&sCepDestino=49045060&nVlPeso=1500.0&nVlComprimento=174,61411571650189&nVlLargura=174,61411571650189&nVlAltura=174,61411571650189&nVlDiametro=0,0&nCdFormato=1&sCdMaoPropria=N&sCdAvisoRecebimento=N&nVlValorDeclarado=0,00&nCdServico=41106,40010&nCdEmpresa=&sDsSenha=&StrRetorno=xml

**Comment by prodis** [comment]
@matheusvetor 
Conforme você adiciona itens no pacote, as dimensões do pacote vão sendo calculadas. Você verificar o valor do comprimento cada vez que você adiciona um novo item ao pacote.
