### ISSUE TITLE
Mostrar resultado na view

### ISSUE THREAD

**Issue by dcalixto** [prodis/correios-frete#14]
Olá, estou usando esse cálculo no controller porém quando coloco  <%= @pac %> ou <%= @sedex %> na vew não está mostrando o valor, alguma coisa está errada? grato

def calculate_ship
  frete = Correios::Frete::Calculador.new :cep_origem => "23970-000",
    :cep_destino => params[:post_code]
    servicos = frete.calcular :sedex, :pac
  @pac = servicos[:pac].valor
  @sedex = servicos[:sedex].valor
  redirect_to checkout_order_path
end

**Comment by prodis** [comment]
Você precisa renderizar a view, não fazer redirect.
