### ISSUE TITLE
webservice responde CEPs inválidos

### ISSUE THREAD

**Issue by rmatuoka** [prodis/correios-frete#17]
testei 2 CEP que não são encontrados pela ferramente BuscaCEP dos correios 78555654 e 70999655, entretanto eu recebo resposta dos correios sem erros e com os valores

**Comment by jpaulo** [comment]
Testei aqui e a gem retornou o valor do frete normalmente pra esses CEPs. Vou colocar aqui a chamada que a gem fez, você pode mudar os valores do cep pra testar você mesmo

http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?sCepOrigem=01451001&sCepDestino=78555654&nVlPeso=0.1&nVlComprimento=28,000000000000004&nVlLargura=25,0&nVlAltura=2,0&nVlDiametro=0,0&nCdFormato=1&sCdMaoPropria=N&sCdAvisoRecebimento=N&nVlValorDeclarado=0,00&nCdServico=41106&nCdEmpresa=&sDsSenha=&StrRetorno=xml

http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?sCepOrigem=01451001&sCepDestino=70999655&nVlPeso=0.1&nVlComprimento=28,000000000000004&nVlLargura=25,0&nVlAltura=2,0&nVlDiametro=0,0&nCdFormato=1&sCdMaoPropria=N&sCdAvisoRecebimento=N&nVlValorDeclarado=0,00&nCdServico=41106&nCdEmpresa=&sDsSenha=&StrRetorno=xml

**Comment by prodis** [comment]
@rmatuoka 
O que é a "ferramenta BuscaCEP" dos Correios?
Você está usando a gem `correios-frete` para calcular frete?

**Comment by rmatuoka** [comment]
tentarei explicar melhor o que foi feito, a ferramente BuscaCEP é uma ferramenta oficial dos Correios, que aceita pesquisas por CEP(retornando endereços) ou por endereços(retornando CEP). os CEPs supracitados fora testado por essa ferramente oficial, que não retornou nenhum endereço para ambos. presumo, com base nisso, que tais ceps não existam na base de dados dos correios. sendo assim não entendo como que o webservice retorna qualquer coisa que não seja um erro de cep inválido.

**Comment by prodis** [comment]
@rmatuoka 
Você tem razão, o frete é calculado mesmo com o CEP de destino inexistente.

```ruby
require 'correios-frete'

frete = Correios::Frete::Calculador.new(
  cep_origem: '90619-900',
  cep_destino: '78555-654',
  peso: 0.3,
  comprimento: 30,
  largura: 15,
  altura: 2
)
frete.calcular_sedex
```

```console
I, [2015-05-06T00:21:47.299130 #98119]  INFO -- : [Correios::Frete] Correios-Frete Request:
GET http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?sCepOrigem=90619-900&sCepDestino=78555-654&nVlPeso=0.3&nVlComprimento=30&nVlLargura=15&nVlAltura=2&nVlDiametro=0,0&nCdFormato=1&sCdMaoPropria=N&sCdAvisoRecebimento=N&nVlValorDeclarado=0,00&nCdServico=40010&nCdEmpresa=&sDsSenha=&StrRetorno=xml

I, [2015-05-06T00:21:48.472124 #98119]  INFO -- : [Correios::Frete] Correios-Frete Response:
HTTP/1.1 200 OK
<?xml version="1.0" encoding="ISO-8859-1" ?>
<Servicos><cServico><Codigo>40010</Codigo><Valor>54,50</Valor><PrazoEntrega>4</PrazoEntrega><ValorSemAdicionais>54,50</ValorSemAdicionais><ValorMaoPropria>0,00</ValorMaoPropria><ValorAvisoRecebimento>0,00</ValorAvisoRecebimento><ValorValorDeclarado>0,00</ValorValorDeclarado><EntregaDomiciliar>S</EntregaDomiciliar><EntregaSabado>N</EntregaSabado><Erro>0</Erro><MsgErro></MsgErro></cServico></Servicos>
````

```ruby
=> #<Correios::Frete::Servico:0x007fdd254d6e58
 @codigo="40010",
 @descricao="SEDEX sem contrato",
 @entrega_domiciliar=true,
 @entrega_sabado=false,
 @erro="0",
 @nome="SEDEX",
 @prazo_entrega=4,
 @tipo=:sedex,
 @valor=54.5,
 @valor_aviso_recebimento=0.0,
 @valor_mao_propria=0.0,
 @valor_valor_declarado=0.0>
```

Acredito que isso aconteça porque o serviço de cálculo de frete usa ranges de CEPs para efetuar o cálculo, e não exatamente o CEP informado. 

Essa dúvida somente quem poderá tirar são os Correios.

**Comment by rmatuoka** [comment]
sim, meu objetivo era te informar, por isso que levantei o issue citando o webservice, não a gem. peço desculpas por qualquer possível grosseria.

**Comment by prodis** [comment]
@rmatuoka 
Não houve nenhuma grosseria. Você trouxe uma situação real e isso é bom para gerar discussão e trazer novas idéias. 

Obrigado.
