### ISSUE TITLE
Código não suportado

### ISSUE THREAD

**Issue by sergiotp** [prodis/correios-frete#27]
Olá! 

Tenho um código de pac com os correios que não é suportado pela Gem.
O código é o seguinte: 4669

Basta incluir esse código na lista de serviços?
A lista está disponível em: https://github.com/prodis/correios-frete/blob/master/lib/correios/frete/servico.rb#L9

Abraços

**Comment by prodis** [comment]
@sergiotp Do you know the name and description of this new PAC service or some available documentation about that from Correios?

Besides, could you send a pull request with this new code? 😉

**Comment by fwuensche** [comment]
@prodis Same for me. I just called Correios and they confirmed our codes are: 

- Sedex: 04162
- PAC: 04669

What should I do to make it work? Just add two new lines to AVAILABLE_SERVICES?
Can I just name them :sedex_com_contrato_6 and :pac_com_contrato_2?

**Comment by prodis** [comment]
@fwuensche Yes, that's it. 
Please send a PR.

**Comment by prodis** [comment]
Solved with version `1.12.0`.
https://rubygems.org/gems/correios-frete/versions/1.12.0
