### ISSUE TITLE
Mudança de códigos pelo Correio

### ISSUE THREAD

**Issue by Revokee** [prodis/correios-frete#29]
Olá,

O Correios fez algumas mudanças recentes nos códigos, porém ainda não foi documentado, posso atualizar os que eu encontrar e fazer um pull request?

![pasted_image_at_2017_05_05_02_17_pm](https://cloud.githubusercontent.com/assets/2688223/25756915/ebd577b8-319e-11e7-854a-e8b3e423c446.png)

**Comment by Revokee** [comment]
Ah já existe o pull request, mas falhou https://github.com/prodis/correios-frete/pull/28

**Comment by deyvin** [comment]
Eu fiz o pull request, na verdade só substitui os códigos mas deu ruim, então fui na gem direto e fiz a substituição no meu projeto

**Comment by lucaszmoraes** [comment]
@deyvin como exatamente você fez?

**Comment by smorigo** [comment]
@lucaszmoraes acredito que ficou faltando os testes

**Comment by henriquesacramento** [comment]
Fiz a mesma implementação porém com testes, seguindo a mesma ideia do #28 no PR #30

**Comment by prodis** [comment]
Thanks @henriquesacramento and everyone. 😉

**Comment by prodis** [comment]
Solved with version `1.11.0`.
https://rubygems.org/gems/correios-frete/versions/1.11.0
