### ISSUE TITLE
Upgrade Nokogiri para (>= 1.8.1) por conta de vulnerabilidades de segurança

### ISSUE THREAD

**Issue by fwuensche** [prodis/correios-frete#36]
A gem atualmente está fixando a versão do Nokogiri em "= 1.7.2", porém:

![image](https://user-images.githubusercontent.com/1740848/34107228-9af868a4-e3e2-11e7-973a-6676811810da.png)

Sabem dizer a razão dessa restrição? 

Vou enviar um PR liberando para "~> 1.8.1", mas fiquem à vontade para recusar caso discordem.

**Comment by prodis** [comment]
Solved in version `1.13.0`.
