### ISSUE TITLE
Dúvidas e Sugestões (2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [prodis/correios-frete#40]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Espero que tenhamos uma resposta satisfatória e um UPGRADE.

**Comment by prodis** [comment]
`correios-frete` é uma gem em Ruby, não funciona em PHP.

**Comment by PauloBoaventura** [comment]
Olá @prodis 

Bom minha dúvida era se esta implementação estava funcionando.
Resumindo...
E o meu problema é colocar uma implementação na plataforma magento 1.9 ou 2.1, que funcione para calculo de frete e que insira o valor deste, no final do pedido.

Se souber algo... Por favor compartilhe!
Abs!
