### ISSUE TITLE
Existe como passar um código específico?

### ISSUE THREAD

**Issue by leonidasamorim** [prodis/correios-frete#45]
Estava tentando passar um código específico pra dentro da chamada. tipo

`frete = Correios::Frete::Calculador.new :cep_origem => "04094-050",
                                        :cep_destino => "90619-900",
                                        :peso => 0.3,
                                        :comprimento => 30,
                                        :largura => 15,
                                        :altura => 2 `
`frete.calcular '3085'`

é possível fazer isso? em vez de usar :pac ou :sedex ? Porque tenho um código de contrato que é específico do cliente e preciso enviar pra fazer o cálculo de de acordo com o contrato dele.

Grato

**Comment by prodis** [comment]
@leonidasamorim Atualmente não há suporte para código de serviços customizados, mas deve ser simples de implementar. 

Você quer abrir um pull request com essa melhoria?
